name: codestyle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-test:
    runs-on: windows-latest
    if: |
      !contains(github.event.head_commit.message, 'skip codestyle')
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Python 3.13
        run: uv python install 3.13
      - name: Run redundancy symbol check
        run: |
          uv run --with regex ./tools/redundancy_symbol.py
      - name: Run typos
        run: |
          uvx typos
      - name: Run ruff linter
        run: |
          uvx ruff check
      - name: Run ruff formatting
        run: |
          uvx ruff format --check
