name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Python 3.13
        run: uv python install 3.13
      - name: Editable install package
        run: |
          uv sync
      - name: Run tests
        run: |
          uv run pytest -v
